const { chromium } = require('@playwright/test');
const fs = require('fs');
const path = require('path');
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8766/');
  await page.getByText('已自动保存',{exact:true}).waitFor();
  await page.locator('#downloadButton:not([disabled])').waitFor();
  await page.screenshot({path:path.resolve('../artifacts/console/editor-desktop.png'),fullPage:true});
  console.log('Initial canvas',await page.locator('#previewCanvas').evaluate(c=>({width:c.width,height:c.height})));
  await page.locator('#blocks textarea').first().fill('网页实时预览测试');
  await page.waitForTimeout(1000);
  console.log('Live preview',await page.locator('#previewState').textContent());
  await page.locator('#addTextButton').click();
  await page.locator('#blocks textarea').last().fill('TEST 12345678');
  await page.waitForTimeout(900);
  const count=await page.locator('#blocks .block').count();
  console.log('Added block count',count);
  await page.locator('#imageFile').setInputFiles(path.resolve('../samples/66.png'));
  await page.locator('#blocks .image-thumb').waitFor();
  await page.waitForTimeout(900);
  const imageBlock=page.locator('.block').filter({has:page.locator('.image-thumb')});
  await imageBlock.locator('select').nth(1).selectOption('90');
  await imageBlock.locator('select').nth(2).selectOption('square');
  await page.locator('#processing').selectOption('dither');
  await page.waitForTimeout(1000);
  await page.screenshot({path:path.resolve('../artifacts/console/editor-image.png'),fullPage:true});
  const downloadPromise=page.waitForEvent('download');await page.locator('#downloadButton').click();const download=await downloadPromise;await download.saveAs(path.resolve('../artifacts/console/browser-export.png'));
  await page.locator('[data-page="settings"]').click();
  await page.locator('input[name="density"][value="dark"]').check();
  await page.locator('#saveSettingsButton').click();
  await page.getByText('默认设置已保存',{exact:true}).waitFor();
  await page.screenshot({path:path.resolve('../artifacts/console/settings-desktop.png'),fullPage:true});
  await page.reload();await page.locator('#downloadButton:not([disabled])').waitFor();
  console.log('Settings persisted',await page.locator('input[name="density"][value="dark"]').isChecked());
  await page.locator('[data-page="editor"]').click();
  console.log('Draft persisted',await page.locator('#blocks textarea').first().inputValue());
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.resolve('../artifacts/console/editor-mobile.png'),fullPage:true});
  console.log('Mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth));
  console.log('Browser errors',errors);
  fs.writeFileSync(path.resolve('../logs/console/browser-check.json'),JSON.stringify({errors,count,mobileOverflow:await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)},null,2));
  await browser.close();
  if(errors.length)process.exitCode=1;
})().catch(error=>{console.error(error);process.exit(1)});
